import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ClientApolloProvider from "./components/ClientApolloProvider"; // Client-side ApolloProvider
import "./global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ClientApolloProvider>{children}</ClientApolloProvider>
			</body>
		</html>
	);
}
